version: '3.8'
services:
  web:
    build: .
    container_name: anikev_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /Anikev_Web
    command: php -S 0.0.0.0:8000 -t .
